spring.application.name=ExperienceUco

# ── Base de datos SQL Server ──────────────────────────────────────────────────
spring.datasource.url=jdbc:sqlserver://localhost:14330;databaseName=UCO_FINCA;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=hermano2013
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ── Hibernate / JPA ───────────────────────────────────────────────────────────
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# ── Swagger / OpenAPI ─────────────────────────────────────────────────────────
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=alpha
